name: django-tenants-practice

services:
  postgres:
    image: postgres
    container_name: postgres-django-tenants-practice
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: