version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-django-tenants
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
